# Generated by Django 4.1.7 on 2023-02-23 10:59

from django.db import migrations, models

def add_offices(apps, schema_editor):
    Office = apps.get_model('your_app_name', 'Office')
    offices = [
        ('Helsinki', 'Helsinki'),
        ('Kuopio', 'Kuopio'),
        ('Oulu', 'Oulu'),
        ('Tampere', 'Tampere'),
    ]
    for office in offices:
        Office.objects.create(office_location=office[0])

class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_public_end',
            field=models.DateTimeField(verbose_name='Release public to'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_public_start',
            field=models.DateTimeField(verbose_name='Release public from'),
        ),
    ]
