# Generated by Django 4.1.7 on 2023-02-23 11:08

from django.db import migrations, models

def add_offices(apps, schema_editor):
    Office = apps.get_model('infoscreen', 'Office')
    offices = [
        ('Helsinki', 'Helsinki'),
        ('Kuopio', 'Kuopio'),
        ('Oulu', 'Oulu'),
        ('Tampere', 'Tampere'),
    ]
    for office in offices:
        Office.objects.create(office_location=office[0])

class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0002_alter_release_release_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=models.CharField(choices=[('helsinki', 'Helsinki'), ('kuopio', 'Kuopio'), ('oulu', 'Oulu'), ('tampere', 'Tampere')], max_length=15),
        ),
        migrations.RunPython(add_offices),
    ]
