# Generated by Django 4.1.7 on 2023-02-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0003_alter_office_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=models.CharField(choices=[('Helsinki', 'Helsinki'), ('Kuopio', 'Kuopio'), ('Oulu', 'Oulu'), ('Tampere', 'Tampere')], max_length=15),
        ),
    ]
