# Generated by Django 4.1.7 on 2023-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0004_alter_office_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_file',
            field=models.TextField(blank=True, default=''),
        ),
    ]
