# Generated by Django 4.1.7 on 2023-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0005_alter_office_office_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_body',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
