# Generated by Django 4.1.7 on 2023-04-25 10:46

from django.db import migrations
from django.contrib.sites.models import Site

def remove_default_site(apps, schema_editor):
    Site.objects.filter(pk=1).delete()

def add_localhost_site(apps, schema_editor):
    Site.objects.create(
        pk=1,
        domain='localhost',
        name='localhost'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('infoscreen', '0006_alter_release_release_body_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_default_site),
        # migrations.RunPython(add_localhost_site),        
    ]

